/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import BackEnd.Eleicao;
import javax.swing.JOptionPane;

/**
 *
 * @author Enzo
 */
public class FoVotar extends javax.swing.JDialog{

   private Eleicao e ;
    public FoVotar(Eleicao e) {
        initComponents();
        this.setModal(true);
        this.e = e;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgOpcoes = new javax.swing.ButtonGroup();
        rbCandidato1 = new javax.swing.JRadioButton();
        rbCandidato2 = new javax.swing.JRadioButton();
        rbCandidato3 = new javax.swing.JRadioButton();
        rbCandidato4 = new javax.swing.JRadioButton();
        rbNulo = new javax.swing.JRadioButton();
        rbBranco = new javax.swing.JRadioButton();
        btnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bgOpcoes.add(rbCandidato1);
        rbCandidato1.setText("Candidato 1");

        bgOpcoes.add(rbCandidato2);
        rbCandidato2.setText("Candidato 2");

        bgOpcoes.add(rbCandidato3);
        rbCandidato3.setText("Candidato 3");

        bgOpcoes.add(rbCandidato4);
        rbCandidato4.setText("Candidato 4");

        bgOpcoes.add(rbNulo);
        rbNulo.setText("Nulo");

        bgOpcoes.add(rbBranco);
        rbBranco.setText("Branco");

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rbCandidato1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(rbCandidato3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbCandidato2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbCandidato4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(83, 83, 83))))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbNulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConfirmar)
                            .addComponent(rbBranco, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(rbCandidato1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbCandidato2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbCandidato3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbCandidato4)
                        .addGap(22, 22, 22))
                    .addComponent(rbNulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbBranco)
                .addGap(18, 18, 18)
                .addComponent(btnConfirmar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if(bgOpcoes.getSelection()==null){
            JOptionPane.showMessageDialog(this,"Favor selecionar o candidato: ");
        }
        else {
            if(rbCandidato1.isSelected()){
                e.setCandidato1();
            }else if(rbCandidato2.isSelected()){
                e.setCandidato2();
            }else if(rbCandidato3.isSelected()){
                e.setCandidato3();
            }
            else if(rbCandidato4.isSelected()){
                e.setCandidato4();
            }
            else if(rbNulo.isSelected()){
                e.setNulos();
            }else {
                e.setBrancos();
            }
            this.dispose(); //Fechar a janela
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgOpcoes;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JRadioButton rbBranco;
    private javax.swing.JRadioButton rbCandidato1;
    private javax.swing.JRadioButton rbCandidato2;
    private javax.swing.JRadioButton rbCandidato3;
    private javax.swing.JRadioButton rbCandidato4;
    private javax.swing.JRadioButton rbNulo;
    // End of variables declaration//GEN-END:variables
}
